Repository atlp-rwanda/atlp-devpulse-fn, pull requests merged in 2024-12, with the labels that each got.

#274 Fix signup
  src/components/form/RegisterForm.tsx
  src/components/validation/Register.tsx
Labels: Ready For Review, BYTE SWAT

#276 #266 A user should be able to comment and react to a blog post
  src/pages/Blogs/BlogComment.tsx
  src/pages/Blogs/BlogReactions.tsx
  src/pages/Blogs/singleBlog.tsx
  src/redux/actions/commentActions.tsx
  src/redux/actions/reactionActions.tsx
  src/redux/actiontypes/commentTypes.tsx
  src/redux/actiontypes/reactionTypes.tsx
  src/redux/index.ts
  src/redux/reducers/commentReducers.ts
  src/redux/reducers/index.ts
  src/redux/reducers/reactionReducers.tsx
Labels: Ready For Review, DREAM

#275 #284 show skeleton on cohort page
  src/components/Cohort/addCohortModal.tsx
  src/components/Cohort/updateCohortmodal.tsx
  src/pages/Cohort/Cohort.tsx
  src/pages/Cohort/CohortDetailPage.tsx
  src/redux/actions/cohortActions.ts
  src/redux/reducers/cohortReducer.ts
  src/skeletons/cohortSkeleton.tsx
  src/skeletons/singleCohortSketon.tsx
Labels: Ready For Review, DREAM

#278 #283 Improve blog card to be clickable
  src/components/home/AboutUs.tsx
  src/components/home/Blogs.tsx
  src/components/home/Header.tsx
  src/components/profileDropdown.tsx
  src/components/sidebar/navHeader.tsx
  src/pages/Blogs/Blogs.tsx
  src/pages/Blogs/singleBlog.tsx
Labels: Ready For Review, DREAM

#288 #172 Export CSV for trainee details
  package.json
  src/components/TraineeDetail/decisionSection.tsx
Labels: Ready For Review, DREAM

#272 #286 Improve user experience by renaming In Application Process
  src/components/TraineeApply/TraineeApply.tsx
  src/components/TraineeApply/TraineeAttributeForm.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applications/ApplicantApplication.tsx
  src/pages/TraineApplicant/Trainee.tsx
Labels: Ready For Review, DREAM

#291 #290 fix add trainee in cohort
  src/pages/Cohort/CohortDetailPage.tsx
  src/redux/actions/cohortActions.ts
Labels: Ready For Review, DREAM

#277 #293 Fix apply job post
  src/components/application/ApplicationFilter.tsx
  src/pages/Applications/ApplicantApplication.tsx
  src/pages/Applications/ViewSingleApplication.tsx
  src/pages/ApplyJobPost.tsx
  src/pages/JobPost/applicantJobFiltering.tsx
  src/pages/SubmitApplication.tsx
Labels: Ready For Review, DREAM

#294 #285 An author will be able to update a blog
  src/components/home/Blogs.tsx
  src/pages/Blogs/Blogs.tsx
  src/pages/Blogs/allBlogs.tsx
  src/pages/Blogs/singleBlog.tsx
  src/redux/actions/blogActions.ts
Labels: Ready For Review, DREAM

#282 Ft schedule tech interview
  .DS_Store
  package.json
  src/assets/Group.svg
  src/assets/assets/NotFoundImg.svg
  src/assets/assets/logo.svg
  src/assets/assets/logoWhite.svg
  src/assets/logo.svg
  src/assets/logoWhite.svg
  src/components/Invitation/ScheduleInterview.tsx
  src/components/Invitation/ScheduleTechnical.tsx
  src/components/form/Button.tsx
  src/components/form/addApplicantScore.tsx
  src/components/iconss/SvgIcons.tsx
  src/pages/ApplicationCycle/myApplication.tsx
  src/pages/TraineApplicant/ApplicantStages.tsx
  src/redux/actions/applicationStage.ts
  src/redux/actions/deletetraine.ts
  src/redux/actions/users.ts
  src/redux/actiontypes/applicationTypes.ts
  src/redux/index.ts
  src/redux/reducers/applicationReducer.ts
  src/redux/reducers/index.ts
  src/redux/reducers/usersReducer.ts
  src/routes/routes.tsx
  src/utils/exports/exportToExcel.ts
Labels: Ready For Review, frontend, BYTE SWAT
