Repository atlp-rwanda/atlp-devpulse-fn, pull requests merged in 2024-10, with the labels that each got.

#169 #168 auth and admin login
  src/components/form/SignInForm.tsx
  src/components/profileDropdown.tsx
  src/pages/LoginPage.tsx
  src/pages/LogoutPage.tsx
  src/pages/PageNotFound.tsx
  src/redux/actions/axiosconfig.ts
Labels: DREAM, Ready For Merge

#172 Fix every faulty navigation
  package.json
  src/components/form/SignInForm.tsx
  src/components/sidebar/navHeader.tsx
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/PageNotFound.tsx
  src/pages/PrivateRoute.tsx
  src/pages/programs/Programs.tsx
  src/pages/programs/UpdateProgram.tsx
  src/routes/routes.tsx
  src/utils/utils.tsx
  yarn.lock
Labels: Ready For Review, DREAM

#179 #148 Add Verify Email
  package.json
  src/components/form/RegisterForm.tsx
  src/components/form/SignInForm.tsx
  src/pages/verifyEmail.tsx
  src/redux/actions/verifyEmailAction.ts
  src/routes/routes.tsx
Labels: Ready For Review, BYTE SWAT

#136 #107 Add entry search
  src/components/sidebar/sidebarItems.tsx
  src/pages/JobPost/job.tsx
  src/pages/TraineApplicant/Trainee.tsx
  src/pages/programs/Programs.tsx
  src/redux/actions/filterProgramActions.ts
Labels: BYTE SWAT, Ready For Merge

#182 Fix fault alerts
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applications.tsx
  src/pages/Applications/AdminViewApplications.tsx
  src/pages/programs/Programs.tsx
  src/redux/actions/adminListApplications.ts
  src/redux/actions/applications.ts
  src/redux/actions/fetchProgramsAction.ts
  src/redux/reducers/applicationReducer.ts
Labels: Ready For Review, DREAM

#181 Admin Dashboard
  .DS_Store
  package.json
  src/.DS_Store
  src/assets/Group (1).svg
  src/assets/Group.svg
  src/assets/Vector.svg
  src/assets/material-symbols_manage-accounts.svg
  src/components/Performance/PerformanceChart.tsx
  src/components/Performance/PerformanceChartGraph.tsx
  src/components/Performance/PerformanceChartHeader.tsx
  src/components/StatCard.tsx
  src/components/form/SignInForm.tsx
  src/components/iconss/SvgIcons.tsx
  src/hooks/useDashboardData.ts
  src/index.css
  src/pages/Dashboard.tsx
  src/redux/actions/cohortActions.ts
  src/redux/actions/filterTraineeActions.ts
  src/redux/actions/programsActions.ts
  src/redux/actions/users.ts
  yarn.lock
Labels: Ready For Review, DREAM

#184 General search and filtration admin
  src/components/SearchBar.tsx
  src/components/SearchResultItem.tsx
  src/components/search/applicationcycles.tsx
  src/components/search/cohorts.tsx
  src/components/search/jobs.tsx
  src/components/search/programs.tsx
  src/components/search/roles.tsx
  src/components/search/trainees.tsx
  src/components/search/users.tsx
  src/components/sidebar/navHeader.tsx
  src/pages/search.tsx
  src/redux/actions/fetchSearchDataAction.ts
  src/redux/actiontypes/fetchSearchDataActionTypes.ts
  src/redux/reducers/fetchSearchDataReducer.ts
  src/redux/reducers/index.ts
  src/routes/routes.tsx
Labels: Ready For Review, DREAM

#197 #105 Ft applicant dashboard
  package.json
  src/assets/assets/calendar.svg
  src/assets/assets/collaborative-learning.svg
  src/assets/assets/performance.svg
  src/assets/assets/strategy.svg
  src/components/form/SignInForm.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applicant/ApplicantDashboard.tsx
  src/redux/actions/TraineeAction.ts
  src/redux/actions/attendanceAction.ts
  src/redux/actions/cohortActions.ts
  src/redux/actions/login.ts
  src/redux/actions/performanceAction.ts
  src/redux/actiontypes/TraineeType.ts
  src/redux/actiontypes/attendanceTypes.ts
  src/redux/actiontypes/cohortTypes.ts
  src/redux/actiontypes/performanceTypes.ts
  src/redux/index.ts
  src/redux/reducers/attendanceReducer.ts
  src/redux/reducers/cohortReducer.ts
  src/redux/reducers/index.ts
  src/redux/reducers/performanceReducer.ts
  src/redux/reducers/traineeReducer.ts
  src/routes/routes.tsx
Labels: BYTE SWAT, Ready For Merge

#199 #107 Fix job Search
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applications.tsx
  src/pages/Applications/AdminViewApplications.tsx
  src/pages/JobPost/job.tsx
  src/redux/actions/filterJobPost.ts
  src/redux/actions/filterProgramActions.ts
Labels: BYTE SWAT, Ready For Merge

#203 #147 Implementing google authentication
  .codeclimate.yml
  src/components/form/GoogleSignup.tsx
  src/components/form/SignInForm.tsx
  src/components/validation/Register.tsx
  src/hooks/useCountry.ts
  src/redux/actions/users.ts
  src/routes/routes.tsx
  yarn.lock
Labels: BYTE SWAT, Ready For Merge

#191 #151 Fixing job application process for an applicant
  src/components/GoogleForm/GoogleRules.tsx
  src/components/GoogleForm/SaveForm.tsx
  src/components/GoogleForm/UpdateSavedForm.tsx
  src/components/GoogleForm/ViewApplicationModal.tsx
  src/components/Tables/DynamicTable.tsx
  src/pages/Applications.tsx
  src/pages/Applications/ApplicantApplication.tsx
  src/pages/JobPost/applicantJobFiltering.tsx
  src/pages/JobPost/job.tsx
  src/pages/JobPost/viewSingleJob.tsx
  src/pages/JobPostDetails.tsx
  src/pages/SubmitApplication.tsx
  src/pages/sharedPosts.tsx
  src/redux/actions/applications.ts
  src/redux/actions/fetchJobPost.ts
  src/redux/actions/fetchSingleJobPostAction.ts
  src/redux/actions/filterJobPost.ts
  src/routes/routes.tsx
Labels: Ready For Review, frontend, BYTE SWAT

#196 applicant notifications
  package.json
  src/App.tsx
  src/components/form/SignInForm.tsx
  src/components/sidebar/navHeader.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/ApplicantNotifications/AppNotification.tsx
  src/routes/routes.tsx
  src/utils/Notifications.tsx
  src/utils/applicantNotifications/NotificationService.ts
  src/utils/applicantNotifications/pusher.ts
  src/utils/applicantNotifications/types.ts
  src/utils/applicantNotifications/useFetchNotifications.ts
  src/utils/applicantNotifications/usePusher.ts
  src/utils/toast.tsx
  src/utils/utils.tsx
Labels: Ready For Review, BYTE SWAT

#224 #158: Preferences/settings page
  src/components/DropdownButton.tsx
  src/components/ToggleSwitch.tsx
  src/components/settings.tsx
  src/components/sidebar/sidebarItems.tsx
  src/routes/routes.tsx
Labels: Ready For Review, DREAM

#227 #161: Skeleton Implementation
  .gitignore
  src/hooks/useDashboardData.ts
  src/pages/ApplicationCycle/ApplicationCycle.tsx
  src/pages/Applications/AdminViewApplications.tsx
  src/pages/Applications/ApplicationsTable.tsx
  src/pages/Dashboard.tsx
  src/pages/JobPost/job.tsx
  src/pages/TraineApplicant/Trainee.tsx
  src/pages/TrainneeDetails.tsx
  src/pages/Trash/Trash.tsx
  src/pages/programs/Programs.tsx
  src/pages/roles&permissions/ListAllUsersPage.tsx
  src/pages/updateTrainee/traineUpdate.tsx
  src/skeletons/adminDashboardSkeleton.tsx
  src/skeletons/applicantEditFormSkeleton.tsx
  src/skeletons/applicantsSkeleton.tsx
  src/skeletons/applicationsSkeleton.tsx
  src/skeletons/buttonSkeleton.tsx
  src/skeletons/cardSkeleton.tsx
  src/skeletons/cycleSkeleton.tsx
  src/skeletons/jobPostSkeleton.tsx
  src/skeletons/memberSkeleton.tsx
  src/skeletons/programSkeleton.tsx
  src/skeletons/sideBarSkeleton.tsx
  src/skeletons/skeletonOfTrash.tsx
  src/skeletons/textSkeleton.tsx
  src/skeletons/traineeInfoSkeleton.tsx
  yarn.lock
Labels: Ready For Review, DREAM

#228 #157 Update profile
  src/assets/cover.png
  src/assets/default-image.jpg
  src/components/profileDropdown.tsx
  src/components/updateUserProfile/imagePreview.tsx
  src/components/updateUserProfile/imageUpload.tsx
  src/components/updateUserProfile/passwordInput.tsx
  src/components/updateUserProfile/profileForm.tsx
  src/components/updateUserProfile/useImagePreview.tsx
  src/pages/Profile.tsx
  src/pages/ProfilePage.tsx
  src/redux/actions/users.ts
  src/redux/index.ts
  src/redux/reducers/getUser.ts
  src/redux/reducers/index.ts
  src/routes/routes.tsx
  src/utils/imageUploadUtil.ts
  src/utils/profileUtils.ts
  src/utils/uploadImageToCloudinary.ts
  src/utils/userSchema.tsx
Labels: Ready For Review, DREAM

#231 fix(#160):Impliment admin Notifications
  src/components/ReusableComponents/Loaders.tsx
  src/components/sidebar/navHeader.tsx
  src/components/sidebar/sidebarItems.tsx
  src/hooks/useAdminNotifications.ts
  src/pages/AdminNotifications/AdminNotifications.tsx
  src/pages/AdminNotifications/Notifications.tsx
  src/pages/AdminNotifications/Pagination.tsx
  src/redux/actions/adminNotifications.ts
  src/routes/routes.tsx
  src/utils/adminNotifications/pusher.ts
  yarn.lock
Labels: Ready For Review, DREAM

#232 #219 Highlight active sidebar item
  src/components/sidebar/sidebar.tsx
Labels: BYTE SWAT, Ready For Merge
