Repository atlp-rwanda/atlp-devpulse-fn, pull requests merged in 2024-11, with the labels that each got.

#212 #164 Admin application list view
  src/components/application/ApplicationActions.tsx
  src/components/application/ApplicationFilter.tsx
  src/components/application/ApplicationRow.tsx
  src/components/application/ApplicationStatus.ts
  src/components/application/ApplicationTable.tsx
  src/components/application/WarningModal.tsx
  src/pages/Applications/AdminViewApplications.tsx
  src/pages/Applications/ApplicationsTable.tsx
  src/pages/Applications/ViewSingleApplication.tsx
  src/skeletons/applicationDetailsSkeleton.tsx
  src/skeletons/applicationsSkeleton.tsx
  yarn.lock
Labels: DREAM, Ready For Merge

#239 fix:admin role and search bar
  src/components/SearchBar.tsx
  src/components/SearchResultItem.tsx
  src/pages/PageNotFound.tsx
  src/routes/routes.tsx
  src/utils/utils.tsx
Labels: Ready For Review, DREAM

#238 #204 fixing authentication issues
  src/components/form/RegisterForm.tsx
  src/components/form/SignInForm.tsx
  src/pages/SignupPage.tsx
  src/redux/actions/users.ts
  src/routes/routes.tsx
  src/utils/utils.tsx
Labels: Ready For Review, BYTE SWAT

#235 Fix token exp
  src/components/form/RegisterForm.tsx
  src/components/sidebar/sidebar.tsx
  src/utils/tokenExpirationHandler.ts
Labels: Ready For Review, BYTE SWAT

#229 fix(#156): have a user be able to apply as a trainee
  src/components/Education.tsx
  src/components/Location.tsx
  src/components/Personal.tsx
  src/components/Tables/DynamicTable.tsx
  src/components/TraineeApply/TraineeApply.tsx
  src/components/TraineeApply/TraineeAttributeForm.tsx
  src/components/TraineeFormPage1.tsx
  src/components/TraineeFormPage2.tsx
  src/components/TraineeSuccess.tsx
  src/components/form/InputField.tsx
  src/components/useFormValidation.tsx
  src/hooks/useTraineeFormLogic.ts
  src/pages/JobPost/applicantJobFiltering.tsx
  src/pages/TraineeApply/TraineeApply.tsx
  src/pages/TraineeApply/TraineeAttribute.tsx
  src/pages/TraineeApply/TraineeSuccess.tsx
  src/redux/actions/TraineeAction.ts
  src/redux/actions/deletetraine.ts
  src/redux/actions/getLoggedUser.ts
  src/redux/actions/traineeAttributes.ts
  src/redux/actiontypes/loggedUserTypes.ts
  src/redux/index.ts
  src/redux/reducers/index.ts
  src/redux/reducers/loggedUser.ts
  src/redux/reducers/traineeReducer.ts
  src/routes/routes.tsx
Labels: Ready For Review, DREAM

#236 Admin be able to advance applicant to next stage
  .codeclimate.yml
  package.json
  src/components/form/SignInForm.tsx
  src/components/form/addApplicantScore.tsx
  src/components/form/advanceTraineeApplicant.tsx
  src/components/form/dismissTraineeApplicationModel.tsx
  src/components/roles&permissions/ListAllUsers.tsx
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/ApplicationCycle/ApplicationCycle.tsx
  src/pages/JobPost/job.tsx
  src/pages/TraineApplicant/ApplicantStages.tsx
  src/redux/actions/applicationStage.ts
  src/redux/actions/deletetraine.ts
  src/redux/actiontypes/applicationTypes.ts
  src/redux/reducers/applicationReducer.ts
  src/redux/reducers/index.ts
  src/routes/routes.tsx
  src/skeletons/applicantStageSkeleton.tsx
  src/skeletons/applicantsSkeleton.tsx
  src/skeletons/loadingSkeleton.tsx
Labels: Ready For Review, BYTE SWAT

#242 #215 Ft tickets page
  src/components/sidebar/sidebarItems.tsx
  src/pages/tickets/adminTicketPage.tsx
  src/pages/tickets/adminTicketResolve.tsx
  src/pages/tickets/applicantTicketReply.tsx
  src/pages/tickets/createTicketModal.tsx
  src/pages/tickets/mobileTicket.tsx
  src/pages/tickets/singleTicketDetails.tsx
  src/pages/tickets/ticketPage.tsx
  src/pages/tickets/ticketPagination.tsx
  src/pages/tickets/ticketSearch.tsx
  src/pages/tickets/ticketTable.tsx
  src/redux/actions/filterTicketsAction.ts
  src/redux/actions/ticketActions.ts
  src/redux/actiontypes/ticketTypes.ts
  src/redux/index.ts
  src/redux/reducers/filterTicketReducer.ts
  src/redux/reducers/index.ts
  src/redux/reducers/ticketReducer.ts
  src/routes/routes.tsx
Labels: BYTE SWAT, Ready For Merge

#251 #252 admin assign a cohort to a trainee
  src/pages/Cohort/CohortDetailPage.tsx
  src/redux/actions/cohortActions.ts
  src/redux/index.ts
  src/redux/reducers/cohortReducer.ts
Labels: Ready For Review, DREAM

#141 Have deployment on Digital ocean using github actions
  .dockerignore
  .github/workflows/docker-img.yml
  Dockerfile
  README.Docker.md
  compose.yaml
  nginx.conf
Labels: WIP, BYTE SWAT, DREAM

#248 Ft blogger
  package.json
  src/components/sidebar/sidebarItems.tsx
  src/components/ui/alert.tsx
  src/pages/Blogs/allBlogs.tsx
  src/pages/Blogs/singleBlog.tsx
  src/redux/actions/blogActions.ts
  src/redux/actiontypes/blogTypes.ts
  src/redux/index.ts
  src/redux/reducers/blogsReducers.ts
  src/redux/reducers/index.ts
  src/redux/reducers/singleBlogReducer.ts
  src/routes/routes.tsx
  src/skeletons/allBlogsSkeleton.tsx
  src/skeletons/singleBlogSkeleton.tsx
  src/utils/imageUploadUtil.ts
  src/validation/blogSchema.ts
Labels: Ready For Review, frontend, DREAM

#258 Blog related Articles
  src/pages/Blogs/singleBlog.tsx
  src/redux/actions/blogActions.ts
  src/redux/index.ts
  src/redux/reducers/blogRelatedArticleReducer.ts
  src/redux/reducers/index.ts
Labels: Ready For Review, DREAM

#259 add trainee role
  src/components/form/SignInForm.tsx
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/Blogs/allBlogs.tsx
  src/pages/PageNotFound.tsx
  src/routes/routes.tsx
  src/utils/utils.tsx
Labels: Ready For Review, DREAM

#261 #247 Applicant upload documents in Cycles Application
  package.json
  src/components/TraineeApply/TraineeApply.tsx
  src/hooks/useTraineeFormLogic.ts
  src/pages/ApplicationCycle/myApplication.tsx
  src/pages/Applications.tsx
  src/pages/TraineApplicant/ApplicantStages.tsx
  src/pages/viewExternalDocuments.tsx
  src/redux/actions/TraineeAction.ts
  src/redux/actions/applications.ts
  src/redux/actions/deletetraine.ts
  src/routes/routes.tsx
Labels: Ready For Review, BYTE SWAT

#260 #264 Admin should be able to hide a blog
  src/components/application/WarningModal.tsx
  src/components/hideBlog.tsx
  src/pages/Blogs/allBlogs.tsx
  src/redux/actions/blogActions.ts
  src/redux/actiontypes/blogTypes.ts
  src/redux/index.ts
  src/redux/reducers/blogsReducers.ts
Labels: Ready For Review, frontend, DREAM

#263 #267 Author should be able to delete a blog
  src/pages/Blogs/singleBlog.tsx
  src/redux/actions/blogActions.ts
Labels: Ready For Review, DREAM

#253 #217 Update profile
  src/assets/andela-logo.svg
  src/components/Layout/Admins/AdminLayout.tsx
  src/components/profileDropdown.tsx
  src/components/settings.tsx
  src/components/sidebar/navHeader.tsx
  src/components/sidebar/sidebar.tsx
  src/components/updateUserProfile/profileForm.tsx
  src/pages/Applicant/ApplicantLayout.tsx
  src/pages/Profile.tsx
  src/pages/ProfilePage.tsx
  src/redux/actions/users.ts
  src/routes/routes.tsx
  src/utils/profileUtils.ts
  src/utils/userSchema.tsx
Labels: BYTE SWAT

#270 Fix: Resolve issues on the landing page for improved functionality
  src/components/home/Blogs.tsx
  src/pages/Blogs/Blogs.tsx
  src/redux/actions/blogsActions.ts
Labels: Ready For Review, DREAM

#256 Sending email invitation for technical assessment
  package.json
  src/components/Cohort/updateCohortmodal.tsx
  src/components/GoogleForm/ApplicationForm.tsx
  src/components/GoogleForm/RecentForms.tsx
  src/components/Invitation/ScheduleTechnical.tsx
  src/components/Layout/Admins/AdminLayout.tsx
  src/components/Personal.tsx
  src/components/country/country.tsx
  src/components/form/advanceTraineeApplicant.tsx
  src/components/pagination2/pagination2.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/ApplicationCycle/ApplicationCycle.tsx
  src/pages/ScheduleInterview.tsx
  src/pages/TraineApplicant/ApplicantStages.tsx
  src/redux/actions/applicationStage.ts
  src/redux/actiontypes/applicationTypes.ts
  src/redux/reducers/applicationReducer.ts
  src/redux/reducers/index.ts
  src/redux/reducers/traineeReducer.ts
  src/routes/routes.tsx
  src/skeletons/technicalSkeleton.tsx
  src/utils/exports/exportToExcel.ts
  tailwind.config.js
Labels: Ready For Review, frontend, BYTE SWAT
