Repository atlp-rwanda/atlp-devpulse-fn, pull requests merged in 2024-09, with the labels that each got.

#119 Feature github actions
  .codeclimate.yml
  .github/workflows/dev-pulse-ci.yml
  package.json
  src/components/GoogleForm/SaveForm.tsx
  src/components/GoogleForm/UpdateSavedForm.tsx
  src/components/GradingBox.tsx
  src/components/ReusableComponents/DataList.tsx
  src/components/ReusableComponents/Select.tsx
  src/components/form/RegisterForm.tsx
  src/components/roles&permissions/ListAllUsers.tsx
  src/pages/updateTrainee/traineUpdate.tsx
  webpack.config.js
Labels: Ready For Review, BYTE SWAT, DREAM

#133 #103 Fixed navigation routing
  src/components/GoogleForm/ApplicationForm.tsx
  src/components/GoogleForm/RecentForms.tsx
  src/components/GoogleForm/SaveForm.tsx
  src/components/GradingBox.tsx
  src/components/Layout/Admins/AdminLayout.tsx
  src/components/ReusableComponents/Select.tsx
  src/components/form/SignInForm.tsx
  src/components/sidebar/navHeader.tsx
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applicant/ApplicantLayout.tsx
  src/pages/ApplicationCycle/ApplicationCycle.tsx
  src/pages/ApplicationForms/CreateApplicantForm.tsx
  src/pages/ApplicationForms/UpdateSavedForm.tsx
  src/pages/ApplicationForms/ViewApplicationForms.tsx
  src/pages/Applications.tsx
  src/pages/Applications/AdminViewApplications.tsx
  src/pages/Applications/ViewSingleApplication.tsx
  src/pages/Dashboard.tsx
  src/pages/FilterTeainee/FilterTrainee.tsx
  src/pages/FilterTeainee/ScoreTypesActions.tsx
  src/pages/FilterTeainee/createScoreType.tsx
  src/pages/GradingSystemPage.tsx
  src/pages/JobPost/job.tsx
  src/pages/JobPost/updateJobPost.tsx
  src/pages/JobPost/viewSingleJob.tsx
  src/pages/LoginPage.tsx
  src/pages/PageNotFound.tsx
  src/pages/SubmitApplication.tsx
  src/pages/TraineApplicant/Trainee.tsx
  src/pages/TrainneeDetails.tsx
  src/pages/Trash/Trash.tsx
  src/pages/importAndSaveManyTraineesFromGoogleSheet/importAndSaveManyTraineesFromGoogleSheet.tsx
  src/pages/programs/Programs.tsx
  src/pages/programs/SingleProgramDetails.tsx
  src/pages/programs/UpdateProgram.tsx
  src/pages/roles&permissions/ListAllUsersPage.tsx
  src/pages/roles&permissions/RolePermission.tsx
  src/pages/sharedPosts.tsx
  src/pages/updateTrainee/traineUpdate.tsx
  src/routes/routes.tsx
Labels: Ready For Review, BYTE SWAT

#130 Fix number can't be shared
  src/components/form/RegisterForm.tsx
Labels: Ready For Review, frontend, DREAM

#128 #102 sidebar links review
  src/components/sidebar/sidebarItems.tsx
Labels: Ready For Review, DREAM

#140 Ft minimize dashboard menu #110
  .codeclimate.yml
  src/components/Layout/Admins/AdminLayout.tsx
  src/components/sidebar/navslide.css
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/Applicant/ApplicantLayout.tsx
  src/pages/LoginPage.tsx
  src/pages/updateTrainee/traineUpdate.tsx
  src/redux/actions/login.ts
Labels: frontend, BYTE SWAT, Ready For Merge

#126 #118 fx: builtinSuperAdminCreateProgram
  src/pages/programs/Programs.tsx
  src/pages/updateTrainee/traineUpdate.tsx
Labels: Ready For Review, DREAM

#139 Ft shareable job post
  src/components/form/SignInForm.tsx
  src/pages/Applicant/ApplicantLayout.tsx
  src/pages/JobPost/job.tsx
  src/pages/JobPost/viewSingleJob.tsx
  src/pages/PrivateRoute.tsx
  src/pages/ShareApplication.tsx
  src/pages/SubmitApplication.tsx
  src/pages/sharedPosts.tsx
  src/pages/updateTrainee/traineUpdate.tsx
  src/redux/actions/fetchSingleJobPostAction.ts
  yarn.lock
Labels: frontend, BYTE SWAT, Ready For Merge

#123 Fix tel
  src/components/form/RegisterForm.tsx
Labels: DREAM, Ready For Merge

#137 Fix/update trainee info
  package.json
  src/components/ReusableComponents/Select.tsx
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/sidebarItems.tsx
  src/index.tsx
  src/pages/TraineApplicant/Trainee.tsx
  src/pages/updateTrainee/locations.ts
  src/pages/updateTrainee/traineUpdate.tsx
  src/pages/updateTrainee/traineeInputs.ts
  src/routes/routes.tsx
Labels: Ready For Review, DREAM

#125 #40 Fix single trainee detail page
  .gitignore
  package.json
  src/components/TraineeDetail/DetailItem.tsx
  src/components/TraineeDetail/ProgramBox.tsx
  src/components/TraineeDetail/decisionSection.tsx
  src/components/sidebar/sidebarItems.tsx
  src/pages/TraineApplicant/Trainee.tsx
  src/pages/TrainneeDetails.tsx
  src/redux/actions/axiosconfig.ts
  src/redux/actions/trainnee.ts
  src/utils/DownloadPdf.tsx
  webpack.config.js
Labels: DREAM, Ready For Merge
